// <auto-generated />
using System;
using Gisys.WebApi.Repository.Gisys;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Gisys.WebApi.Migrations
{
    [DbContext(typeof(GisysContext))]
    [Migration("20210224110358_GisysDb-v1")]
    partial class GisysDbv1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Gisys.WebApi.Repository.Gisys.Consultant", b =>
                {
                    b.Property<Guid>("ConsultantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("consultantId");

                    b.Property<int>("ChargedHours")
                        .HasColumnType("int")
                        .HasColumnName("chargedHours");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("YearOfEmployment")
                        .HasColumnType("int")
                        .HasColumnName("yearOfEmployment");

                    b.HasKey("ConsultantId");

                    b.ToTable("Consultant");
                });

            modelBuilder.Entity("Gisys.WebApi.Repository.Gisys.NetResult", b =>
                {
                    b.Property<Guid>("NetResultId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("netResultId");

                    b.Property<int>("Net")
                        .HasColumnType("int")
                        .HasColumnName("net");

                    b.HasKey("NetResultId");

                    b.ToTable("NetResult");
                });
#pragma warning restore 612, 618
        }
    }
}
